;EasyRC一键装机配置文件,如需启用配置功能,请删除字段的开头符号  ;  分号及删除后面的注释
;其他高级功能请仔细阅读 优捷易产品文档中心 https://open.51cxsoft.com/
;部分功能自定义需付费为VIP会员,详情请访问http://www.51cxsoft.com/ujyvip/
;请注意本配置文件的文本编码需为 [Ansi] 编码
[Config]
;Search=1 ;1仅搜索U盘；Search=2 仅搜索光盘；Search=3  仅搜索磁盘；Search=4  搜索全部磁盘；Search=0或为空  不搜索镜像
;SearchSize=300 ;定义程序搜索镜像时最低镜像大小,以(MB)为单位,如填300,则小于 300MB 的镜像文件跳过搜索不载入,最低可填 1 ,代表小于 1MB 的镜像文件跳过搜索不载入
;SearchDepth=3 ;定义程序扫描镜像文件的目录深度,默认为3
;WimCore=2 ;定义恢复WIM/ESD/SWM的核心,1 为Imagex,2为wimlib-Imagex,3为Dism核心,NT5.X系统不生效
;bootName=Windows一键急救系统
;VolumeLabel=1 ;0或留空为默认关闭还原后修改安装分区卷标名称,1为开启自动设置,其他为分区卷标名称
;restart=1 ;定义完成后是否自动重启/关机, 1  为完成后不进行重启/关机操作,2为默认关机，其他为默认重启
;AutoInstallOS= ;定义是否自动安装Windows,1为不自动安装,其他默认为自动安装
;Recovery=1 ;定义是否在恢复系统后默认安装急救系统,1为恢复后安装,2为恢复后安装但在成功进入桌面后清除急救系统,其他为默认不安装
;AllFixBoot=1 ;1为切换引导分区至自动模式
;check=0 ;1为默认还原时校验镜像文件完整性,其他为默认不校验
;UserName=1 ;启用自定义用户名功能,如值为1时则在部署时自动根据当前电脑的品牌厂家名称创建用户名,如为0或空则不启用该功能,其他字符则为在部署时根据自定义名称创建用户名
;OSSafe=1 ;启用更多选项-查杀强制捆绑病毒木马,1为启用,其他为默认不启用
;skipTips=0 ;0为关闭程序启动时的提示窗口,其他为默认开启
;AutoRunDrv=1 ;1为开启更多选项-[搜索并运行万能驱动]，具体参考 技术支持文档：https://www.yuque.com/youjieyi-r2ahq/cmo2fu/lfgazxnm85m64q31
;AutoRunNetDrv=0 ;0为开启更多选项-[搜索并运行万能驱动]-[仅搜索本地];其他为默认为开启更多选项-[搜索并运行万能驱动]-[搜索本地与在线]
;Wimlibforce=1 ;1为开启Wimlib核心还原wim/esd时即使文件损坏也强制还原，不建议默认开启本项
;DriverBackup=1 ;1为开启【安装前备份驱动】-【导入新系统】;2为开启【安装前备份驱动】-【仅备份】;3为开启【安装前备份驱动】-【强制导入到新系统】
;NewPCName=定义计算机名 ;1为 PC-[日期][随机] ;2为 PC-[日期];3为 随机;4为 系统默认;留空为 PC-[日期][随机],其他字符则为计算机名,文档：https://www.yuque.com/youjieyi-r2ahq/cmo2fu/ctd7s2si771xa7gg?singleDoc
;ZrPE=1 ;1为开启更多选项-提前注入WinPE急救系统,需先开启上方的 Recovery=1 ，本配置项需开通VIP才可生效,免费方式为手动勾选在更多选项-提前注入WinPE急救系统
;RemoveRecovery=1 ;1为开启更多选项-安装急救系统后手动清理,开启后程序在进入桌面后不会清理PE急救系统并在桌面生成一个手动清理快捷方式
;ZNZYPage=1 ;1为开启更多选项-智能转移pagefile.sys虚拟内存文件,开启后将自动根据系统环境转移到D盘,重启系统后生效
;AutoUSB3=1 ;1为开启更多选项-导入USB3驱动[Win7X64],开启后将自动导入win764位的USB3驱动;0为关闭，空为开启
;AutoNVME=1 ;1为开启更多选项-导入Nvme补丁驱动[Win7X64],开启后将自动导入win764位的NVME补丁;0或空为关闭;建议将[Win7NvmeHotfix.XIM]放置于UjyQii.exe同目录下的bin文件夹
;DektopRunDevmgmt=1 ;1为启用[更多选项-进入桌面后运行设备管理器],其他为保持默认;
;AutoZwjc=1 ;1为启用[更多选项-检测并开启指纹/面部识别支持[Win10/11],其他为保持默认;开启后程序将自动检测识别是否存在指纹/面部硬件并开启相关支持


[OSYh]
;RemoveLinkIcons=1 ;1为启用[更多选项-优化设置-移除快捷方式小箭头],其他为保持默认;
;ShowAllTypes=1 ;1为启用[更多选项-优化设置-显示[所有文件扩展名]],其他为保持默认;
;DisableHibernate=1 ;1为启用[更多选项-优化设置-禁用系统休眠],其他为保持默认;
;DisableAutoPlay=1 ;1为启用[更多选项-优化设置-禁用自动播放],其他为保持默认;
;EnableDarkTheme=1 ;1为启用[更多选项-优化设置-开启主题深色模式],其他为保持默认;
;DisplayMyComputericon=1 ;1为启用[更多选项-优化设置-桌面显示[此电脑]图标],0为不启用,其他为默认启用;
;DisableSystemRestore=1 ;1为启用[更多选项-优化设置-禁用系统还原],其他为保持默认;
;DisableGameDVR=1 ;1为启用[更多选项-优化设置-禁用游戏录制工具],其他为保持默认;
;OSRetention=1 ;1为启用[更多选项-优化设置-禁用系统保留空间],其他为保持默认;
;DisableOSUpdate=1 ;1为启用[更多选项-优化设置-禁用系统自动更新],2为启用[更多选项-优化设置-阻断系统更新[慎用]],其他为保持默认;
;DisableSystemVersionUpdate=1 ;1为启用[更多选项-优化设置-禁用系统大版本更新],其他为保持默认;
;DisablewindowsDefender=1 ;1为启用[更多选项-优化设置-禁用Windows Defender],2为启用[更多选项-优化设置-移除Windows Defender],其他为保持默认;
;TaskbarGlomLevel=1 ;1为启用[更多选项-优化设置-从不合并任务栏],其他为保持默认;
;RemoveUWP=1 ;1为启用[更多选项-优化设置-移除内置UWP应用[保留基础应用]],其他为保持默认;
;DisableUAC=1 ;1为启用[更多选项-优化设置-禁用用户账户控制[UAC]],0为不启用,其他为默认启用
;EnableFirewall=1 ;1为启用[更多选项-优化设置-禁用系统防火墙],其他为保持默认;
;HideCopilot=1 ;1为启用[更多选项-优化设置-隐藏任务栏的Copilot(AI助手)],其他为保持默认;
;HideSmallComponents=1 ;1为启用[更多选项-优化设置-隐藏任务栏的小组件],其他为保持默认;
;HideTaskViewButton=1 ;1为启用[更多选项-优化设置-隐藏任务栏的任务视图],其他为保持默认;
;SilentInstalledAppsEnabled=1 ;1为启用[更多选项-优化设置-禁止自动安装推荐的应用],其他为保持默认;
;showDesktopNETIcons=1 ;1为启用[更多选项-优化设置-显示桌面[网络]图标],其他为保持默认;
;showDesktopIEIcons=1 ;1为启用[更多选项-优化设置-显示桌面[IE浏览器]图标],其他为保持默认;
;showDesktopControlIcons=1 ;1为启用[更多选项-优化设置-显示桌面[控制面板]图标],其他为保持默认;
;HideSearchboxTaskbarMode=1 ;1为启用[更多选项-优化设置-藏任务栏的搜索框],其他为保持默认;
;HideFeeds=1 ;1为启用[更多选项-优化设置-隐藏任务栏的资讯兴趣],其他为保持默认;
;HidePeopleBar=1 ;1为启用[更多选项-优化设置-隐藏任务栏的聊天/人脉],其他为保持默认;
;NodataTips=1 ;1为启用[更多选项-优化设置-跳过数据在所在国家之外处理],其他为保持默认;
;RemoveOneDrive=1 ;1为启用[更多选项-优化设置-禁用OneDrive网盘],其他为保持默认;
;NoWin10UpdataTools=1 ;1为启用[更多选项-优化设置-隐藏win10升级助手],其他为保持默认;
;DisableCortana=1 ;1为启用[更多选项-优化设置-禁用多嘴的小娜],其他为保持默认;
;DisableRecordRecentFiles=1 ;1为启用[更多选项-优化设置-禁止记录最近文件],其他为保持默认;
;RestoreClassicsMenu=1 ;1为启用[更多选项-优化设置-恢复win11经典右键菜单],其他为保持默认;
;HideFolderIcon=1 ;1为启用[更多选项-优化设置-隐藏此电脑的七个文件夹],其他为保持默认;
;skipcheckTpm=0 ;0为关闭[更多选项-优化设置-绕过Win11硬件限制],其他为默认开启
;skipBitLocker=0 ;0为关闭[更多选项-优化设置-关闭BitLocker自动加密],其他为默认开启
;DisableWINJJ=1 ;1为启用[更多选项-优化设置-关闭Windows聚焦],其他为保持默认;
;Win11TaskbarKz=1  ;1为启用[更多选项-优化设置-Win11任务栏靠左],其他为保持默认;
;PowerPlan=3 ;1为启用[更多选项-优化设置-电源计划:平衡]；2为启用[更多选项-优化设置-电源计划:节能]；3为启用[更多选项-优化设置-电源计划:高性能]；4为启用[更多选项-优化设置-电源计划:卓越性能]
;PowerMonitor=1 ;1为启用[更多选项-优化设置-电源:从不关闭显示器],其他为保持默认;
;PowerStandby=1 ;1为启用[更多选项-优化设置-电源:计算机从不休眠],其他为保持默认;
;DisableDOR=1 ;1为启用[更多选项-优化设置-禁用传递优化],其他为保持默认;
;DisableBypassNRO=0 ;0为不启用[更多选项-优化设置-绕过BypassNRO.cmd限制],其他为保持默认;
;QzshowDesktopIEIcons=1 ;1为启用[更多选项-优化设置-Win10/11强制创建IE浏览器桌面图标],其他为保持默认;


[Task]
;VIP功能,需开通vip会员
;task1=
;定义程序运行后的运行第三方程序的操作,支持定义恢复后运行、部署中运行、首次进桌面运行、恢复后删除文件、部署中恢复后删除文件、首次进桌面恢复后删除文件,详情看支持文档
;文档：https://www.yuque.com/youjieyi-r2ahq/cmo2fu/dxdk51fg86i96hw5

[WanDrv]
;在本地安装系统时通过配置文件自动选择万能驱动,详情请仔细阅读 https://www.yuque.com/youjieyi-r2ahq/cmo2fu/lfgazxnm85m64q31
Win7X86=
Win7X64=
Win10X64=
Win10X86=
Win8X64=
Win8X86=
Win8.1X86=
Win8.1X64=
WinXPX86=

[OSInstall]
File=

[OEMInformation]
;OEM信息自定义
;Manufacturer=
;SupportURL=
;Model=
;SupportHours=
;SupportPhone=
;RegisteredOrganization=
;RegisteredOwner=


[RemoveAppx]
;更多选项-优化设置-移除内置UWP应用[保留基础应用]自定义列表
;默认为保留应用商店、APPX安装程序、计算器、记事本、Windows终端,如需移除请删除开头 ; 符号
Clipchamp.Clipchamp
Microsoft.549981C3F5F10
Microsoft.BingNews
Microsoft.BingWeather
Microsoft.BingFinance
Microsoft.BingFoodAndDrink
Microsoft.BingHealthAndFitness
Microsoft.BingMaps
Microsoft.BingSports
Microsoft.BingTravel
Microsoft.Bing
Microsoft.Camera
Microsoft.GamingApp
Microsoft.GetHelp
;Microsoft.DesktopAppInstaller
;Microsoft.HEIFImageExtension
;Microsoft.HEVCVideoExtension
;Microsoft.MicrosoftEdge.Stable
;Microsoft.RawImageExtension
;Microsoft.SecHealthUI
;Microsoft.StorePurchaseApp
;Microsoft.VCLibs.140.00
;Microsoft.VP9VideoExtensions
;Microsoft.WebMediaExtensions
;Microsoft.WebpImageExtension
;Microsoft.WindowsCalculator
;Microsoft.WindowsNotepad
;Microsoft.WindowsStore
;MicrosoftWindows.Client.WebExperience
;Microsoft.WindowsTerminal
Microsoft.Getstarted
Microsoft.MicrosoftOfficeHub
Microsoft.MicrosoftSolitaireCollection
Microsoft.MicrosoftStickyNotes
Microsoft.Paint
Microsoft.People
Microsoft.PowerAutomateDesktop
Microsoft.ScreenSketch
Microsoft.Todos
Microsoft.Windows.Photos
Microsoft.WindowsAlarms
Microsoft.3DBuilder
Microsoft.WindowsCamera
microsoft.windowscommunicationsapps
Microsoft.WindowsFeedbackHub
Microsoft.Appconnector
Microsoft.WindowsMaps
Microsoft.WindowsSoundRecorder
Microsoft.Xbox.TCUI
Microsoft.XboxGameOverlay
Microsoft.XboxGamingOverlay
Microsoft.XboxIdentityProvider
Microsoft.XboxSpeechToTextOverlay
Microsoft.YourPhone
Microsoft.ZuneMusic
MSTeams
Microsoft.Windows.DevHome
Microsoft.ZuneVideo
Microsoft.BingSearch
MicrosoftCorporationII.QuickAssist
MicrosoftCorporationII.MicrosoftFamily
MicrosoftWindows.CrossDevice
Microsoft.Microsoft3DViewer
Microsoft.OutlookForWindows
Microsoft.MixedReality.Portal
Microsoft.MSPaint
Microsoft.Wallet
Microsoft.XboxApp
Microsoft.HelpAndTips
Microsoft.Office.OneNote
Microsoft.Reader
Microsoft.SkypeApp
Microsoft.WindowsReadingList
Microsoft.WindowsScan
Microsoft.XboxLIVEGames
Microsoft.Office.Sway
microsoft.microsoftskydrive
Microsoft.CommsPhone
microsoft.windowsphotos
Microsoft.Print3D
Microsoft.Messaging
Microsoft.WindowsPhone
Microsoft.OneConnect
Microsoft.WebMediaExtensions
Microsoft.Edge.GameAssist